### ISSUE TITLE
Migrate to Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by chalin** [envoyproxy/envoy-website#273]
This issue is part of a CNCF-wide effort to upgrade project websites to GA4 since **Google has deprecated Universal Analytics** (UA). For more details, see:

- https://github.com/cncf/techdocs/issues/108, including reference to a suggested [migration process](https://github.com/cncf/techdocs/blob/main/docs/analytics.md#migrating-to-google-analytics-4), which we've used to [migrate a few CNCF projects](https://docs.google.com/spreadsheets/d/1Mx4LhdI2Un-rvGMI73SlHxQH9D2HABAJclMB3dd6lnA) already.

### Tasks: stages 1, 2 & 3

- [x] Create a GA4 site tag under the **CNCF projects** account.
  The new GA4 stream measurement ID is: **`G-DXJEH1ZRXX`**
- [x] [Connect] to the UA site tag from the GA4 tag.
- [x] Add Netlify snippet injection, only for production deploys:
  ```js
  {% if CONTEXT == 'production' %}
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-DXJEH1ZRXX"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
  
    gtag('config', 'G-DXJEH1ZRXX');
  </script>
  {% endif %}
  ```
- [x] Ensure that the GA4 site tag is receiving events.
- [x] Drop UA Jekyll config - #276

/cc @caniszczyk @nate-double-u

---

### Tasks: prep

I'm noticing that UA GA was added via:

- #124

and that despite all the source files still being present, I'm not seeing any evidence of the `UA-148359966-1` site tag being used in any of the ep.io pages. Might analytics have been inadvertently removed?

I've raised a separate issue for this:

- #274

[connect]: https://support.google.com/analytics/answer/9973999
[gtag.js]: https://developers.google.com/analytics/devguides/collection/gtagjs

**Comment by phlax** [comment]
> Might analytics have been inadvertently removed?

i have asked in the past about getting access to the analytics as it would be helpful in understanding any issues with the website (eg heavy traffic)

cc @mattklein123

**Comment by chalin** [comment]
I'd like to request access to the analytics too.

**Comment by mattklein123** [comment]
I think I have access to the Analytics and can probably figure out how to give it out. Please ping me on Envoy slack.

**Comment by chalin** [comment]
Thanks @mattklein123. I just pinged you from the CNCF slack workspace.

**Comment by chalin** [comment]
As @phlax points out just above this https://github.com/envoyproxy/envoy-website/issues/274#issuecomment-1262918574, there's no GA associated with the docs, since they are generated separately. @phlax's suggestion of using Netlify snippet injection would be a clean and simple solution to get analytics into all of the site pages.

**Comment by chalin** [comment]
Oh, I remember now why we have moved away from snippet injection for another project. As far as I recall, snippet injection is applied to all builds, not just production builds. Maybe that's configurable? I'll take another / closer look tomorrow.

**Comment by phlax** [comment]
its also not as configurable - but the alternative is manually injecting the snippet into historical pages and adding the snippet to new docs builds - doable but probs not the easiest way

**Comment by chalin** [comment]
- Oh, snippets are actually nicely configurable. I'll work on something today.
- I'm going ahead and creating the GA4 site tag, which we'll need regardless if we ever gain access to the UA property.

/assign @chalin

**Comment by chalin** [comment]
Production-only snippet injection has been enabled, and I've checked a branch deploy to ensure that it isn't getting any dynamic snippet injection.

The GA4 site tag is processing events:

> <img width="550" alt="image" src="https://user-images.githubusercontent.com/4140793/193275662-aac6b2a1-5f51-4922-8e5f-977e046c5f8e.png">

**Comment by chalin** [comment]
Whether we ever recover the UA access, the work here is done. Closing.
